fix: issue with vercel build with rust default toolchain
bumped from 1.81.0 to 1.82.0

Error in vercel

```
error: $HOME differs from euid-obtained home directory: you may be using sudo
error: $HOME directory: /vercel
error: euid-obtained home directory: /root

...

error: failed to compile `wasm-bindgen-cli v0.2.92`, intermediate artifacts can be found at `/tmp/cargo-installJWGtrj`

...

Error: Command "bash vercel-build.sh" exited with 101

```